version: "3.8"

services:
    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        volumes:
            - sql-data:/var/opt/mssql
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=T3stPswd1
        ports:
            - "1433:1433"

volumes:
    sql-data:
